collections:
  pages:
    path: ''
    output: true
    name: Pages
    editor:
      type: page
    inputs:
      title:
        type: text
      body:
        type: markdown
paths:
  static: public
  uploads: public/uploads
timezone: Asia/Tokyo
markdown:
  engine: commonmark
  options:
    gfm: true

  admin:
    path: admin
    output: false
    name: Admin
    editor:
      type: data
    inputs:
      setting:
        type: text

paths:
  static: public
  uploads: public/uploads

timezone: Asia/Tokyo

markdown:
  engine: commonmark
  options:
    gfm: true
