collections:
  pages:
    path: /
    output: true
    editor:
      type: page
      inputs:
        title:
          type: text
        body:
          type: markdown

  admin:
    path: admin
    output: false
    editor:
      type: data
      inputs:
        setting:
          type: text

paths:
  static: public
  uploads: public/uploads

timezone: Asia/Tokyo

markdown:
  engine: commonmark
  options:
    gfm: true
