backend:
  name: github
  repo: poyo9210/grashurion-dictionary
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "ページ"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
